---
- name: Stop and disable timer
  ansible.builtin.systemd:
    name: "container-s3s-{{ item.name }}.timer"
    scope: user
    enabled: no
    state: stopped
  loop: "{{ s3s_config }}"

- name: Stop service
  ansible.builtin.systemd:
    name: "container-s3s-{{ item.name }}.service"
    scope: user
    state: stopped
  loop: "{{ s3s_config }}"

- name: Delete timer unit file
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/systemd/user/container-s3s-{{ item.name }}.timer"
    state: absent
  loop: "{{ s3s_config }}"

- name: Delete service unit file
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/systemd/user/container-s3s-{{ item.name }}.service"
    state: absent
  loop: "{{ s3s_config }}"

- name: Delete s3s container
  containers.podman.podman_container:
    name: "s3s-{{ item.name }}"
    state: absent
  loop: "{{ s3s_config }}"

- name: Delete config directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/s3s"
    state: absent

