---
- name: Create temporarily directory
  ansible.builtin.tempfile:
    state: directory
  changed_when: no
  register: tempdir

- name: Copy Containerfile
  ansible.builtin.template:
    src: Containerfile.j2
    dest: "{{ tempdir.path }}/Containerfile"
  changed_when: no

- name: Pull base image
  containers.podman.podman_image:
    name: docker.io/library/python
    tag: "{{ s3s_python_version }}-{{ item }}"
    force: yes
    state: present
  loop:
    - buster
    - slim

- name: Build s3s container image
  containers.podman.podman_image:
    name: s3s
    path: "{{ ansible_user_dir }}/s3s/"
    force: yes
    state: build
  register: build_image

- name: Set SELinux file context
  community.general.sefcontext:
    target: "{{ ansible_user_dir }}/.config/s3s(/.*)?"
    setype: container_file_t
    state: present

- name: Create config directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/s3s"
    state: directory

- name: Copy s3s config if previous version existed
  ansible.builtin.copy:
    src: "{{ ansible_user_dir }}/s3s/config.txt.{{ item.name }}"
    dest: "{{ ansible_user_dir }}/.config/s3s/{{ item.name }}.txt"
    remote_src: yes
  ignore_errors: yes
  loop: "{{ s3s_config }}"

- name: Create s3s config
  ansible.builtin.copy:
    content: "{{ config_data | to_nice_json }}"
    dest: "{{ ansible_user_dir }}/.config/s3s/{{ item.name }}.txt"
    force: no
  vars:
    config_data:
      api_key: "{{ item.api_key | default('') }}"
      acc_loc: "{{ item.acc_loc | default('') }}"
      gtoken: "{{ item.gtoken | default('') }}"
      bullettoken: "{{ item.bullettoken | default('') }}"
      session_token: "{{ item.session_token | default('') }}"
      f_gen: "{{ item.f_gen | default('https://api.imink.app/f') }}"
  loop: "{{ s3s_config }}"

- name: Create s3s container
  containers.podman.podman_container:
    name: "s3s-{{ item.name }}"
    image: s3s
    command: "python s3s.py -r{{ '-nsr' if not item.salmon | default(False) }}{{ ' --blackout' if item.blackout | default(False) }}"
    interactive: yes
    tty: yes
    volume:
      - "{{ ansible_user_dir }}/.config/s3s/{{ item.name }}.txt:/app/config.txt"
    generate_systemd:
      path: "{{ ansible_user_dir }}/.config/systemd/user"
    recreate: "{{ build_image.changed }}"
    state: present
  loop: "{{ s3s_config }}"

- name: Copy timer unit file
  ansible.builtin.template:
    src: container-s3s.timer.j2
    dest: "{{ ansible_user_dir }}/.config/systemd/user/container-s3s-{{ item.name }}.timer"
  vars:
    name: "{{ item.name }}"
    delay: "{{ item.timer_delay | default('5min') }}"
  loop: "{{ s3s_config }}"

- name: Start and enable timer unit
  ansible.builtin.systemd:
    name: "container-s3s-{{ item.name }}.timer"
    scope: user
    enabled: yes
    state: started
    daemon_reload: yes
  loop: "{{ s3s_config }}"

- name: Stop old salmon timer unit"
  ansible.builtin.systemd:
    name: "container-s3s-{{ item.name }}-salmon.timer"
    scope: user
    enabled: no
    state: stopped
  loop: "{{ s3s_config }}"
  failed_when: no

- name: Remove old salmon timer unit
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/systemd/user/container-s3s-{{ item.name }}-salmon.timer"
    state: absent
  loop: "{{ s3s_config }}"
  notify: systemd daemon-reload

- name: Remove old salmon service unit
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/systemd/user/container-s3s-{{ item.name }}-salmon.service"
    state: absent
  loop: "{{ s3s_config }}"
  notify: systemd daemon-reload

- name: Remove old salmon container
  containers.podman.podman_container:
    name: "s3s-{{ item.name }}-salmon"
    state: absent
  loop: "{{ s3s_config }}"

