---
- name: Checkout s3s
  ansible.builtin.git:
    repo: https://github.com/frozenpandaman/s3s.git
    dest: "{{ ansible_user_dir }}/s3s"
    depth: 1
    single_branch: yes
  register: s3s_git

- name: Copy Containerfile
  ansible.builtin.template:
    src: Containerfile.j2
    dest: "{{ ansible_user_dir }}/s3s/Containerfile"

- name: Pull base image
  containers.podman.podman_image:
    name: docker.io/library/python
    tag: "{{ s3s_python_version }}-{{ item }}"
    force: "{{ s3s_git.changed }}"
    state: present
  loop:
    - buster
    - slim

- name: Build s3s container image
  containers.podman.podman_image:
    name: s3s
    path: "{{ ansible_user_dir }}/s3s/"
    force: "{{ s3s_git.changed }}"
    state: build

- name: Create s3s config
  ansible.builtin.copy:
    content: "{{ config_data | to_nice_json }}"
    dest: "{{ ansible_user_dir }}/s3s/config.txt.{{ item.name }}"
  vars:
    config_data:
      api_key: "{{ item.api_key | default('') }}"
      acc_loc: "{{ item.acc_loc | default('') }}"
      gtoken: "{{ item.gtoken | default('') }}"
      bullettoken: "{{ item.bullettoken | default('') }}"
      session_token: "{{ item.session_token | default('') }}"
      f_gen: "{{ item.f_gen | default('https://api.imink.app/f') }}"
  loop: "{{ s3s_config }}"

- name: Create s3s container
  containers.podman.podman_container:
    name: "s3s-{{ item.name }}"
    image: s3s
    command: "python s3s.py -r -nsr"
    interactive: yes
    tty: yes
    volume:
      - "{{ ansible_user_dir }}/s3s/config.txt.{{ item.name }}:/app/config.txt:z"
    generate_systemd:
      path: "{{ ansible_user_dir }}/.config/systemd/user"
    recreate: "{{ s3s_git.changed }}"
    state: present
  loop: "{{ s3s_config }}"

- name: Create s3s container for salmon
  containers.podman.podman_container:
    name: "s3s-{{ item.name }}-salmon"
    image: s3s
    command: "python s3s.py -r -osr"
    interactive: yes
    tty: yes
    volume:
      - "{{ ansible_user_dir }}/s3s/config.txt.{{ item.name }}:/app/config.txt:z"
    generate_systemd:
      path: "{{ ansible_user_dir }}/.config/systemd/user"
    recreate: "{{ s3s_git.changed }}"
    state: present
  when: item.salmon | default(False)
  loop: "{{ s3s_config }}"

- name: Copy timer unit file
  ansible.builtin.template:
    src: container-s3s.timer.j2
    dest: "{{ ansible_user_dir }}/.config/systemd/user/container-s3s-{{ item.name }}.timer"
  vars:
    name: "{{ item.name }}"
    delay: "{{ item.timer_delay | default('5min') }}"
  loop: "{{ s3s_config }}"

- name: Copy timer unit file for salmon
  ansible.builtin.template:
    src: container-s3s.timer.j2
    dest: "{{ ansible_user_dir }}/.config/systemd/user/container-s3s-{{ item.name }}-salmon.timer"
  vars:
    name: "{{ item.name }}-salmon"
    delay: "{{ item.timer_delay | default('5min') }}"
  when: item.salmon | default(False)
  loop: "{{ s3s_config }}"

- name: Start and enable timer unit
  ansible.builtin.systemd:
    name: "container-s3s-{{ item.name }}.timer"
    scope: user
    enabled: yes
    state: started
    daemon_reload: yes
  loop: "{{ s3s_config }}"

- name: Start and enable timer unit for salmon
  ansible.builtin.systemd:
    name: "container-s3s-{{ item.name }}-salmon.timer"
    scope: user
    enabled: yes
    state: started
    daemon_reload: yes
  when: item.salmon | default(False)
  loop: "{{ s3s_config }}"

