FROM docker.io/library/python:{{ s3s_python_version }}-buster AS builder
WORKDIR /
COPY requirements.txt /
RUN pip install -r requirements.txt

FROM docker.io/library/python:{{ s3s_python_version }}-slim
WORKDIR /app
COPY --from=builder /usr/local/lib/python{{ s3s_python_version }}/site-packages /usr/local/lib/python{{ s3s_python_version }}/site-packages
COPY iksm.py /app
COPY s3s.py /app
COPY utils.py /app
CMD [ "python", "s3s.py" ]

