FROM docker.io/library/python:{{ s3s_python_version }}-buster AS builder
WORKDIR /
RUN set -x \
 && git clone --depth 1 https://github.com/frozenpandaman/s3s.git \
 && pip install -r /s3s/requirements.txt

FROM docker.io/library/python:{{ s3s_python_version }}-slim
WORKDIR /app
COPY --from=builder /usr/local/lib/python{{ s3s_python_version }}/site-packages /usr/local/lib/python{{ s3s_python_version }}/site-packages
COPY --from=builder /s3s/iksm.py /app
COPY --from=builder /s3s/s3s.py /app
COPY --from=builder /s3s/utils.py /app
CMD [ "python", "s3s.py" ]

